apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "nginx-11"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
    ports:
  - name: http
    nodePort: 32358
    protocol: TCP
  - name: https
    nodePort: 30956
    protocol: TCP
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx"
        image: "nginx:latest"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-1"
    apiVersion: "apps/v1beta1"
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

